### ISSUE TITLE
Few Recommendations for Unlock

### ISSUE THREAD

**Issue by Pr0t0ns** [deepakkumar132/Discord-Token-Generator#2]
Hello, I just wanted to suggest features that might be able to make this generate unlocked because as of now it definitely generates locked tokens or very low quality tokens.

1. Seems like you are missing headers in some of the requests for example the fingerprint request
2. TLS Client doesn't support chrome 111 (they support up to 110)
3. Using V10 of discords API when it's not even used by default for production yet
4. Missing Cookies. It looks like you don't even pass in when sending a POST to the register endpoint 
5. Seems like you're mixing headers some of your headers are capitalized which means it's meant for HTTP/2 and some aren't which means it's meant for HTTP/1.1

Their is a few other big things you're missing but I'm not going to mention them right now if I have time I will make a PR

**Comment by deepakkumar132** [comment]
OK SIR TODAY I WILL UPDATE THE GEN THANKS YOU FOR TALL US
